FROM bde2020/spark-python-template:3.0.0-hadoop3.2

MAINTAINER Alex Kotopoulis <alex@kotopoulis.com>

ENV SPARK_APPLICATION_PYTHON_LOCATION /app/dataframe.py
ENV SPARK_APPLICATION_ARGS ""

ENV SPARK_SUBMIT_ARGS "--executor-memory 5G"
